apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app-with-metrics: quarkus-orders
    k8s-app: quarkus-orders
  name: quarkus-orders
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
      scheme: http
  selector:
    matchLabels:
      app: quarkus-orders
