kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: order-store-fe
  labels:
    app: order-store-fe
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: order-store-fe
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None

