kind: Secret
apiVersion: v1
metadata:
  name: basic-user-pass
  namespace: store-project-build-env
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    tekton.dev/git-0: 'https://github.com'
data:
  password: Z2hwX2hHaW9lbHpDWWI4Z3RCaGRjUXRRVlRrYzVNRXJTNDRVREhIVg==
  username: bWNvbWJp
type: kubernetes.io/basic-auth
  
