apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: store-project-build-env
resources:
  - pipeline.yaml
  - s2i-task.yaml
  - storage-class.yaml
  - pvc.yaml
#  - promote-pipeline.yaml
  - github-secret.yaml
  - promote-task.yaml
  - quay-secret.yaml
  - github-service-account.yaml
  - update-config-version-task.yaml
  - update-config-version-task-test.yaml
  - triggers/trigger-template.yaml
  - triggers/trigger-binding.yaml
  - triggers/trigger.yaml
  - triggers/github-secret.yaml
  - triggers/event-listener.yaml
  - triggers/route.yaml

