kind: Secret
apiVersion: v1
metadata:
  name: postgresql
  labels:
    template: postgresql-ephemeral-template
    template.openshift.io/template-instance-owner: 7faa6627-e4af-4212-90e3-506864cbaf70
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
    argocd.argoproj.io/sync-wave: "0"
data:
  database-name: b3JkZXJzZGI=
  database-password: b3JkZXJzcGFzc3dvcmQ=
  database-user: b3JkZXJzdXNlcg==
type: Opaque
