apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: store-demo-test
resources:
  - database-secret.yaml
  - database.yaml
  - database-service.yaml
  - kafka.yaml
  - orders-topic.yaml
