apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: store-demo-test
resources:
  - quarkus-orders.yaml
  - service.yaml
  - route.yaml
#  - service-monitor.yaml
commonLabels:
  app: quarkus-orders