apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: store-project
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: store-project-trigger