apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: store-project-trigger
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: store-project
  template:
    ref: store-project