apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra

spec:
  project: store-demo
  source:
    repoURL: 'https://github.com/mcombi/store-demo-project.git'
    path: store-common-config/kustomize/base
    targetRevision: develop
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: store-demo-test
  syncPolicy:
    automated:
        selfHeal: false
    syncOptions:
      - CreateNamespace=true