---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: store-project-build-env
spec:
  encryptedData:
    password: AgA6WQZpuub7WBzYIZddvq/VS4SedoEkUCQTvp55x5qa6uaPevK3gK4LYkXlA/DO0O3y5A2gGFzRbJj9ujQhNC5OdBgmfkwiD162LZuP/Lzg2Hap/l3BM2Bqh5KpCaTzij8aWXhR2JN+O5JGxEb2x6+ojkAOYDKlviUEaKwaIJ2XdLp2u0yonjj2QBkNjLCgTB7VyDYU4T5F3tnEQVaE9WfLJ4UOhWrb2VsUctz/4pTVOGwZzxBg1GPTmaR4dfEIwksa+yhRRfGiIjyaLtdS47aAFepsfn6OvCLOJSfu8kvHcsqpFKG+Q3BVu7qunKVY3duvKUxBm8AsRRSNO6CYrKUKJKO2egju89n4pECG0CfnUEQnAPLtTnDbD4rkht9HEEPnvHBZzUOuzCMxGgnPlfzRu+bOeIQXBs8tOZClDa/l3c9i/BDWGRPO0cEUwkPeVyLScnt3fAaLi5pb8Fm2xNNEtvfo/BBkOwA9JtY4r0FS2SvlOEi+SH9KGLj+BzqfdBbNk2yFNXvwtxdbDj97g0IhTkKqSq1cx/T2O5PDcelycENEBASiTi+/9H5AiCcCkwfAsNtnlZqTahxrGfHGoiMAyEY2CC2iEedPZKmeJuklUJXwuLV6+HfTINjwnFgDZTLDL+mXjRPwlA83mk/+yjFhIpnUkAIhPq3ZRLgGBk7gOkKCwi8SN61dbTjvLDoN6jU5gxe5eQux6foWejOWUwlnHaxVee8nJPFr8hl+6HOL0ltq4rxBNYPSZ6GRiP0+tZ8owcZ6fwqooPAz4aSrFkvygfQBnU4mmj2+JTR/nOfBveQxaOi0cECmyLUU6Io=
    username: AgC6IPmcQg1/6YR435Zx1j2wSA2sFeft0mNxUUlcxpnXPra4Xa3RnlIYTsszNBbM2niQZSebkCsYFdhIPpdpTZVUGPNQiGuco+kAqD1OY/yHZeB7v53UxpydjSjKz7h5ahbGGjKbJE2XcZWyfSn2mB9H3aAd/j4SvT6l5M3Nd1pxx0HTwpYGlnoEkLq3KxKXWrEvsfRWoAGSUtbKWZm6JspYreyRyX4qQ7imFVplVunlQFyfn31X2i2yCw3oCFnTlVOLyLR0feKGH8/vIDcwUazMkUU4MCtS1EC6KoZljnbgUFVNvK0enV9GRGK9vb4ER5wDDEIh3opYcyI22XMjXNevcCwA70c+ZexDTDelpLTXo54oRZwX9n8J2TSPbqEYG6lCywswydlKV/I1iI3eLr7RiWyH10eylxh3zBhwlzXJ84NEUkY5JvMSH5FPfj25u3qgxpvVYzpA4xfwcQUvLViUolzx1NA24YjmIjFs5/xLc6WGWcjodRuvtVXx8vOynbWWtW84AQK9c1q20HGXFdakGLgD+ewz62BhPYyIsUKlDjthsYA3MuW3HphWKYhOBZQBlnPrruyBHuQtDdU8n55rUffb5jTLtR44Nge/kKFQbcUM43MQNaEVKN2+C4e6LPQijx9caNmT6MPZtCM7DtP1PnuECeO/14nnkQr6O5p4pltCxa040ve+4VDFbqdVk+8J+gLMbBE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: store-project-build-env
    type: kubernetes.io/basic-auth
