kind: Secret
apiVersion: v1
metadata:
  name: basic-user-pass
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"
    tekton.dev/git-0: 'https://github.com'
data:
  username: CHANGE_ME
  #the forllowing is the base64 encoding for the tokent
  password: CHANGE_ME

type: kubernetes.io/basic-auth