apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: default
spec:
  encryptedData:
    password: AgAFNpiF2XncrMUK/OMgzZYoDuT3hH6q4CPjXhV4n48H/i186+ig0C7ZMEkJZmKkFLqMK2bQmGsfzT3yYzlk51Yh58cKceMgvb8eHDEU0hg0pFIGfeLmyncuJHI/n0JS9meGD28E6/itRLWkfuGL/RTE0dvwyGTvTZJ/QqJnA7WZfrj0INA/JGUbtGgOlhAm8lPa99gF0mI6XSTnjpGZpb7dvVuFebLzBEFJ8JApxSaiKYW6qOX+5U+qAZjn3r56pU8k1ayF9JmH/sun1EUytXiZrrwwUrshkhNgjWDHIV8NZvpPHp843jMfoIW7RRtOoERCucbxR3gNQkEy0xgBU8NstiHD/zoYdpHRpaEdzcsm4Pz0RaLmZSLxMmG/9V1gnlYV/OBFJsXysfizEUAGE9P3VTUpGg51g9WxNduhNYjm1xxj0e2lOTlZuUqihFksxc8tdSBqMs1bgpyZCnH2jq/lDgKyJ506httmFwYIUC4kdnc6l5CQs3XV8tUN0gF5rZXkKR54Oe1B2HrHFnQWzEA2nGc8+nM5FPwgv8+ZWwytKycWQtjD2/RqsK/JP012IZm5DPUFuFXbvG4JEL0L5EjycS8pYPfLf2yjK1qW8I4lq9ds3fpD73Lx3AJwbFAfQLqxpB/B5TtkWshW5e4O5mUSlJG2lMt1/0WGR9mw1L+0XL0Hnt99y8VX+Il14Z5r/IwRtBYMaYJ/AxiZtmaqnnJfvgxYznboNHWPv9BsWF8yWhdnbv2R9uEb8IcY3pW4eqImysQ6wAsZbZAMttt7q2hnN2CbqVfjDr6Vlm0NlCQROjFzUWNsf4vY0G07y4A=
    username: AgAPg5QXgJxYXsIJcb5qH81GhuJkAsfmB826/JxZvwQrwEcFoVUnSi0iuDlEg1nJHq5w/Wal438DyUcO9+ZQseHuAAQZfkl5ho573xitEvHaw1G8STq2b0Cv3Jkm2byMbYvGATTzDbbsCw0YW9CS3yQnhnQoYE2Pl6dCABD8Ie3Dib4j5atBSw2KX81bZAEZBTQqu+GbFYSvWH9547AT8d+YWLWmJacYnxNSUEZIN4s9pVh3bn0Pi/wkRWUH2i8W9poxHwMbvk3aMtrplZzb/UKbi2IyNuwLDIcAz7FAwj7vko72T0Voocu4tiJj3b9fDmpIPqSHjU0KZeoEWjLnzPB8IFPPvwzxkVlBGFQ51hsod+oZlnrhkvGMpXyQV5+Mcg3pusEysvK95M5YK7KI92cFfntSAHtB5tWsLIeVXpff9JNrLkEnLtyLbnr3PrAmMU1WlYrEECGZbzSduy/hjDlhWuWopWl1OUI+PGEDPpy5anbBD2zWIrPixv1o+xJLwYlf4HPEbn8jdk4DSxQCyOpFQHtWv7R+9B9BvJszkOZn6qzaEV57gSyLJEfKnltBuzCzdojBVLtfRITzDKwMot3EPkgKyCDHkNbaMdhdsld556sp9aPFbBtyC3HCs/ZFEhXAYek4saDQupr6d5qBT046ePz9a5c7bG76E+vE7gsjBQVCe/fw+auLZERYj8cLpFi+FfDHMnQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: default
    type: kubernetes.io/basic-auth

