---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: store-project-build-env
spec:
  encryptedData:
    password: AgChRHgzvXaOUSPrvUUaDuaTkIK8H38NKdBZ5osl7/mhbhQKJkcQPknUHSUVigfLiOQn1ND9B8IOJLaVCEriWH6++vyShTsQdL4oetsfg+ptlU2yiBvWYt4dcx7m4L8aCwGredcUQP5wA4r5CHa/+VsZDa+mcZlrdJetRyCrRb0WKy7seXXAJfNFcdGZzMt9cNHBXN3BJ0TzkvzJlV1Xl6kN+t8msC9n9fzFsN+Lm4LCTZF36UIQKTky+xMHRtxvP7itQZ6PC+tonF16dwk4/rcpAzyMBHARkp4U5bjh1N9d4X3PQQ9xyktO+9OlMYsKNz5P34P0E3lj1N8Zsbpe9+G5pgmCPefpbffdQDqIsM7kQi4XQxemgdfsYBZF+29EHSI5kY1mgRfV0BsTPHrm/KjVd6ZCQSpX0AcYJcfHSAWzbsMFAlYnTqCcHA6DkJ8V/pK2o5ZRczwVTkxAsuyB/t93UmO3J9gpZBwsXC0Lr+md49JTvZ+aG+X7j4mZ1mvq04k2A1hBnEXEMhn4FRS8APM/uQv6U92zrkxaxEVrB6ORGkfEDfXeoFoOGkzFghxMu9B/3IxlX5n7dC3OFSnX3dt50hNv1D8R99YWVP8n+nb7zNp8TvaZjqP7GEkAgvsWBt55mIpNHj6LFZPe7hRvNifRDNRWlsWfms1rxYHMeqRvSb9D0L5Dj9D++5A8vifhfolykYq+8Tf/WISzKwpWzOQWMNqIcUu7h0PxcjbsyHwpYZ6zx2xeV9mnB5Ckxk9YG+c3cyK8MTNZAUr2yfb33dNPshKKZp74ddAxHHrfdSQ+q/nEa7zTxllZ3cqKNAQ=
    username: AgCCcxJjnsVCWK5ag9XnKI8lxYq2II0m/0jYGRiAWH+VU0+cIWNFo2Uqvll23/uYVKMgEGF4ZuH9NvGyC2RQ8bIgfdkhgtMZkHV+U0LTbIfalDiFwGSbfkP66R56Lz8UgK9BReOQVYlL61oka4aHHAn2LTr8F1RdjipZBNpv3O/iTfr7Lca9HVbFV+NMvwdddxKdb5o5AFJCFj91od22z9kmLLS9hI6HxroRINl4ZOJ4/OZdMU1f6IfCxYkH0zn5GVcHYZa/XprYuHPdaQT55U7V6whHfQpmhmkKuiYKXXws22/EUgERNbh/84MYjwa12AVi7hmCFalg6bab/KBx9clZyW/vta8kc1BkkHBqKwhbFdxcfqRb1hBhgDICvglZm3s0YJgwnh5TEcq+PK3ZknYHNcXly3JxkyDQVfvnT4F4/SKjtNUpZnSh3zYVrLAaPWo8AOthPQlpmfpD8RD6JvJ1KZLWvF0b3qap2URVEnc0UVwB3pm3zx2EhzV/llLyazN/kkR4+vG5pfeVryqiEBzPkgbNXkKxFvaz1vdut1Ef260m1g1rxYeCJEF9VTslouXoNmk+YfOIgfbQ5QrQkV15xF6IHsuZypFa2uzNmE/AdbgllAW4OqXhBJI80aLnnhX7TaEeIUsdobptaVWdOh8tGYwk2jlX3QH9BESVU4z9r3vRAzWs5OL1YvzuW5jMWMeTT0O0mpQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: store-project-build-env
    type: kubernetes.io/basic-auth
