kind: Secret
apiVersion: v1
metadata:
  name: basic-user-pass
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"
    tekton.dev/git-0: 'https://github.com'
data:
  username: bWNvbWJp
  #the forllowing is the base64 encoding for the tokent
  password: Z2l0aHViX3BhdF8xMUFYMzZPMlkwUExEUXdacnVpUHNoX1NqWTFtSm5lMHRQZ1dseVEzWWgybnlWUVMwN2RGb2NWUmVYekJiSElEYm5MSk1PTk9JNUUycXZTM3Bj

type: kubernetes.io/basic-auth