apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: store-project-build-env
spec:
  encryptedData:
    password: AgBZ7q1uD3LjCA3T0MXhDU13lvkR/fWQ47BS8zekN6StV04n6rnuYfeTKSGpZ+atcV8RVJAwDKkYbPAotd6BenaM0tSBcEG/VftKzWDS7bCzPZ+2TKHrXd5I94sHDfKZtDInqxzycq8xmT290DmBsYlGNj0ibe0IP+y+YJdK4w5/D+PJNV+Tqkf8orTJvUyheYX7MTBK9cbkqrr5H3tpmssdGM1t4hLcz6t4Y2js93BgfAP2p9f5l6XnIY7YX+Z6LFTfd64kMrkPWoJuxSfCiuF1xiZaXQSyhcVLiyceK8dzkFcdsuy6za+FaGs/mY8Jr5Ryt5iX+GXgQCe6yMGpBzxFqJhwdie7kF5Zz0sn1zPiU60Xn62sDfCmjjRWGKWYlGvh49uXqWFifjZRMbJsztNK56/1PBtR32eeXNImiU/01Y9ZFuIgI3i9yd2LwwT20bSJ/Y0aY6riVktmw6MySZygH6nqmI4482TRCOn0tYN9ph0bHgIchQ0TymR+XbpbysVdE4xoBAnL3keSdFjHkLrqXin4N/qyUTIhOro2O1fWLQQ+3GHB4fiK+pkBf6fw0MYnujxhIPSBWOAgNvzqKvowkvoD+0hA/1vBtVuervdA4whUI3stL1pLRY+j9vT1+RkIFIu6t5c6cMDXv/80hhtCWpN8c1djB9iroM3/Od6VEIgY1grLo6GJZa6vB7tO+LoC2mAJ0uwbrZlNkdw4UQFXfJmL08lr/KzEy1NN+VWetAPtCeuDRD6i6ijkmpmy/QmI2J8iLcxDODSEQWWqumdclJVEVfN7RtABy+pf8NdSMrHUOXppEDH2iLqtKFE=
    username: AgCKAzpVT6F84dylKqcAx6Ckr7OFQKFA642eE6hM6mxTK/ead/rnxW/r9newUkXTm7nPeGQgjdHnrJNFDHSOFmGaPYeBQGEQ/zllVd1iYSfsGQnlfr20KVxwp3xVK7UuNj0njZtlxaXs/i0aNnbCL5Hk5FRzJaymWs+WpG++haGxxAL3Y0COTgP6gVmCknHnyEDOapFWZo1Stcbx1cbW9cVA4zqDJR1ai2U8DGv5ELeyjyyVxRoAW5ic2VGZDc3wYiA2okaF8S+lkivnms2FmryLn0DtDKL5MELvWiHRi8K6MjOxtM2rtDTefyn4ni1z6QMYGVcU8wcox7IFPoGn8b9elWAH3SZ+4DAcpj4BKRsaMZWnQ71YKUiz9jA8ZLIwc8n+1B6vNkjv5t4MtI3SJvHReOzLafyNV4xKBoF41R0lKvqS3y5vZNx0T84CZ+1HXLFi8Mw3zlOFkDLmFLxhffEXY6CtgvGH3uvMLiL0bZk2TwsuuldYW4rAP7CDZl7v55l8Gj4JSwSU1GsdG1VyU7I94UmlLAy7O5vf1AGagMVJIu3efHnSsnW9MdOr8WD3EjhsbJYEId5wNUTN04BQiXP6kYNJqlPhIUch9LY44Fg6F6v0yU2zlsD3KoEvFCDiAvtDNLHdsF7uzKZ6JYmRxCAwJEwO1nGA1W/EnpPq+Fb2jTG4UO8P/noqHgMgJ2izP/FqAu07mLM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: store-project-build-env
    type: kubernetes.io/basic-auth

